name: Wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/get_it
  get_it: ^4.0.4
  # https://pub.dev/packages/http/install
  http: ^0.12.2
  # https://pub.dev/packages/shared_preferences/install
  shared_preferences: ^0.5.8
  # https://pub.dev/packages/device_info/install
  device_info: ^0.4.2+6
  # https://pub.dev/packages/flutter_splash_screen/install
  flutter_splash_screen: ^0.1.0
  # https://pub.dev/packages/modal_progress_hud/install
  modal_progress_hud: ^0.1.3
  # https://pub.dev/packages/loading_indicator/install
  loading_indicator: ^1.2.0
  # https://pub.dev/packages/connectivity/install
  connectivity: ^0.4.9
  # https://pub.dev/packages/flutter_html/install
  flutter_html: ^0.11.1 
  # https://pub.dev/packages/url_launcher/install - To Open App links
  url_launcher: ^5.5.0
  # https://pub.dev/packages/cached_network_image/install
  cached_network_image: ^2.3.1
  # https://pub.dev/packages/permission_handler/install
  permission_handler: ^5.0.1+1
  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # https://pub.dev/packages/ntp/install
  auto_size_text: ^2.1.0
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^6.1.2
  # https://pub.dev/packages/shimmer/install
  shimmer: ^1.1.1
  # https://pub.dev/packages/flutter_screenutil/versions/4.0.2+3/install
  flutter_screenutil: 4.0.2+3
  # https://pub.dev/packages/background_app_bar/install
  background_app_bar: ^2.0.1
  # https://pub.dev/packages/another_flushbar/install
  another_flushbar: ^1.10.28
  # https://pub.dev/packages/pie_chart/install
  pie_chart: ^5.3.0
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/heebo_regular.ttf
    - family: CaveatBrush
      fonts:
        - asset: assets/fonts/caveat-brush_regular.ttf
    - family: Sansation
      fonts:
        - asset: assets/fonts/sansation_regular.ttf